source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '5.0'

target 'QCloudSDK_Example' do
    pod 'QCloudSDK', :path => '../'
    pod 'QCloudSDK/Upload', :path => '../'
    pod 'QCloudSDK/Download', :path => '../'

    target 'QCloudSDK_Tests' do
        inherit! :search_paths
        
        
    end
end
