source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '5.0'

target 'QCloudSDK_Example' do
    pod 'QCloudSDK', '1.1.4.2'
    pod 'QCloudSDK/Upload', '1.1.4.2'
    pod 'QCloudSDK/Download', '1.1.4.2'

    target 'QCloudSDK_Tests' do
        inherit! :search_paths
    end
end
